#---------------------------------#
#      general configuration      #
#---------------------------------#

# Avoid cloning the entire repo, only get last commit
clone_depth: 1

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master


#----------------------------------#
#  cache third party dependencies  #
#----------------------------------#
cache:
- c:\3rdparty -> appveyor.yml, download_dependencies.bat

#---------------------------------#
#           build matrix          #
#---------------------------------#
environment:
  matrix:
    # Visual Studio 2015 - 32 bit
    - Name: v140-x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      Generator: Visual Studio 14 2015
    # Visual Studio 2015 - 64 bit
    - Name: v140-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015 
      Generator: Visual Studio 14 2015 Win64
    # Visual Studio 2017 - 32 bit
    - Name: v141-x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      Generator: Visual Studio 15 2017
    # Visual Studio 2017 - 64 bit
    - Name: v141-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      Generator: Visual Studio 15 2017 Win64

clone_folder: c:\projects\osg-3rdparty-cmake

#----------------------------------#
# install third party dependencies #
#----------------------------------#
install:
- cmd: IF NOT EXIST "c:\3rdparty" download_dependencies.bat


#---------------------------------#
#       build configuration       #
#---------------------------------#


build_script:
- cmd: >-
    mkdir build
    
    cd build
    
    cmake c:\projects\osg-3rdparty-cmake -G "%Generator%" -DZLIB_SOURCE_DIR=c:/3rdparty/zlib -DLIBPNG_SOURCE_DIR=c:/3rdparty/libpng -DLIBJPEG_SOURCE_DIR=c:/3rdparty/libjpeg -DLIBTIFF_SOURCE_DIR=c:/3rdparty/tiff -DFREETYPE_SOURCE_DIR=c:/3rdparty/freetype -DGLUT_SOURCE_DIR=c:/3rdparty/glut -DGIFLIB_SOURCE_DIR=c:/3rdparty/giflib -DMINIZIP_SOURCE_DIR=c:/3rdparty/minizip -DCURL_SOURCE_DIR=c:/3rdparty/curl -DCMAKE_INSTALL_PREFIX="C:/projects/osg-3rdparty-cmake/build/3rdParty/%Name%"
    
    cmake --build . --config "Debug" --target install 
    
    cmake --build . --config "Release" --target install 
    
    cd 3rdparty\%Name%
    
    7z a c:\projects\osg-3rdparty-cmake\%Name%.zip . 

artifacts:
- path: '%Name%.zip'
  name: '%Name%'

